### ISSUE TITLE
Implement --auto-settle-off receiver and sender option

### ISSUE THREAD

**Issue by jirkadanek** [rh-messaging/cli-proton-ruby#10]
Test test_reply_to_address in JAMQMsgPatternsfffTests fails with

    stderr: "/home/jdanek/Work/repos/cli-proton-ruby/lib/options/sr_common_option_parser.rb:55:in `parse\': invalid option: --reactor-auto-settle-off (OptionParser::InvalidOption)"

Example client invocation

```
cli: "aacf"
type: "sender"
options: "--log-msgs"
options: "dict"
options: "--count"
options: "4"
options: "--broker"
options: "amqp://127.0.0.1:5672/JAMQMsgPatternsfffTestsNm8HjYj"
options: "--msg-reply-to"
options: "JAMQMsgPatternsfffTestsNm8HjYj-replyQ"
options: "--msg-content-map"
options: "text=Reply to message delivery test with random string replyQ_4"
wrapperOptions {
}
```

**Comment by rkubis** [comment]
Sender is setting auto-settle-off when sending.

Receiver is setting auto-settle-off when processing reply-to.
