### ISSUE TITLE
Implement --reactor-prefetch option

### ISSUE THREAD

**Issue by jirkadanek** [rh-messaging/cli-proton-ruby#20]
Needed in for example JAMQConnectionfffTests#test_slow_consumer_is_killed

**Comment by jirkadanek** [comment]
@rkubis have you already clarified if the proton-ruby client even supports configuring message prefetch size at this point? CC @alanconway

**Comment by rkubis** [comment]
@jdanekrh I was not able to find setting of prefetch in new reactor, I saw it only in old implementation.

**Comment by ssorj** [comment]
It would be called credit_window in any new Proton API work.
http://home.apache.org/~jross/pumpjack/core/receiver-options/index.html#flow-control

I see it here:
http://qpid.apache.org/releases/qpid-proton-master/proton/ruby/api/Qpid/Proton/Receiver.html#open-instance_method

**Comment by rkubis** [comment]
Implemented.
