### ISSUE TITLE
Implement --anonymous option

### ISSUE THREAD

**Issue by jirkadanek** [rh-messaging/cli-proton-ruby#22]
Needed in for example JAMQConnectionfffTests.test_send_empty_message_by_connection_level_sender

**Comment by rkubis** [comment]
This feature is used to send message over "anonymous" sender in javascript/nodejs.

It means that client is able to do `connection.send(message)` without `open_sender`.

It looks that this is not possible in Qpid Proton Ruby library.

Do we need this?

**Comment by jirkadanek** [comment]
Could be that you `open_sender` with `nil` address, or you leave the address parameter out. In Java, JMS, this would be the first case, passing `null` somewhere in `JMSProducer` creation.

**Comment by ssorj** [comment]
I've tried that and it works.

https://github.com/ssorj/messaging-examples/blob/master/qpid-proton-ruby/respond.rb#L38

**Comment by rkubis** [comment]
Thanks a lot, Justin!

**Comment by rkubis** [comment]
Workaround exists, implementation of this option is not blocked, for now.
