### ISSUE TITLE
Implement --conn-heartbeat option

### ISSUE THREAD

**Issue by rkubis** [rh-messaging/cli-proton-ruby#35]
Heartbeat is idle_timeout in connection.

**Comment by jirkadanek** [comment]
We should have this already, https://github.com/rh-messaging/cli-proton-ruby/blob/c1e6718ac58d8432ed911ff324afc234e3191ee8/lib/options/basic_option_parser.rb#L116

**Comment by rkubis** [comment]
You are right, https://github.com/rh-messaging/cli-proton-ruby/issues/23, closing.
