### ISSUE TITLE
implement --content-type sender option

### ISSUE THREAD

**Issue by jirkadanek** [rh-messaging/cli-proton-ruby#9]
Test test_publish_subscribe_int in JAMQMsgPatternsfffTests fails with message

    stderr: "/home/jdanek/Work/repos/cli-proton-ruby/lib/options/sr_common_option_parser.rb:55:in `parse\': invalid option: --content-type (OptionParser::InvalidOption)"

Example client invocation

```
cli: "aacf"
type: "sender"
options: "--msg-content"
options: "12345"
options: "--log-msgs"
options: "dict"
options: "--count"
options: "3"
options: "--content-type"
options: "int"
options: "--broker"
options: "amqp://127.0.0.1:5672/topic://JAMQMsgPatternsfffTestsnxTwlvp"
wrapperOptions {
}
```

**Comment by rkubis** [comment]
I think this is same as --msg-content-type and can be closed.

**Comment by jirkadanek** [comment]
It is not the same.

In cli-proton-python, `--msg-content-type` value is assigned into `msg.content_type`.

The `--content-type` is instead used to cast the value of `--msg-content`, `--msg-content-list-item`, and also the value of `--msg-property` and `--msg_content_map_item`, if they are specified with = and not ~.

See the usages of https://github.com/rh-messaging/cli-proton-python/blob/eef1d544433a994b68f675b991715be8198f83fc/cli_proton_python/utils.py#L118-L137

**Comment by rkubis** [comment]
Oh, now I see.
